### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'ix'

### ISSUE THREAD

**Issue by lmlodda** [jeffmacinnes/glassesCalibration#1]
Dear Jeff,

i would like to test the Gaze Mapping Pipeline with a test recording using Tobii Pro Glasses 2. I copied the folder from the raw data containing the file segment.json to my test folder. I specified a target folder and started the tobii_preprocessing. Here comes the output. I received an error message saying there is no attribute ix... What can i do? Thanks for your help.

gazeMappingPipeline/glassesCalibration/gazeMappingPipeline$ python3.8 tobii_preprocessing.py /media/data_2/ETRA/DASC2021/TestGMP/raw/session_7/projects/c36niyr/recordings/6odloqe/segments/1/ /media/data_2/ETRA/DASC2021/TestGMP/target/
Copying raw data...
Input data copied to: /media/data_2/ETRA/DASC2021/TestGMP/target/2017_09_13/07-50-14
Prepping gaze data...
Traceback (most recent call last):
  File "tobii_preprocessing.py", line 274, in <module>
    preprocessData(args.inputDir, args.outputRoot)
  File "tobii_preprocessing.py", line 41, in preprocessData
    gazeWorld_df, frame_timestamps = formatGazeData(newDataDir)
  File "tobii_preprocessing.py", line 109, in formatGazeData
    raw_df = json_to_df(join(input_dir, 'livedata.json'))
  File "tobii_preprocessing.py", line 241, in json_to_df
    df.ix[df.index < min(sorted(vts_sync.keys())), 'vts_time'] = np.nan		# set rows that occur before the first frame to nan
  File "/home/lmlodda/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5465, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ix'

**Comment by mehshankhan** [comment]
it solve it by using the previous version of pandas and numpy.
pandas = 0.19.2
numpy = 1.7.0
